### ISSUE TITLE
求助呀，模拟器打开项目时报错

### ISSUE THREAD

**Issue by Buddha** [yannliao/threejs-example#18]
VM26:1 thirdScriptError
Mf.now is not a function
TypeError: Mf.now is not a function
    at http://127.0.0.1:24286/appservice/libs/three.weapp.js:347:241
    at http://127.0.0.1:24286/appservice/libs/three.weapp.js:1:582
    at http://127.0.0.1:24286/appservice/libs/three.weapp.js:1:684
    at require (http://127.0.0.1:24286/appservice/__dev__/WAService.js:2:1789576)
    at http://127.0.0.1:24286/appservice/__dev__/WAService.js:2:1789186
    at http://127.0.0.1:24286/appservice/pages/animation/index.js:3:19
    at require (http://127.0.0.1:24286/appservice/__dev__/WAService.js:2:1789576)
    at <anonymous>:38:7
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:24286/appservice/appservice?t=1587292098445:1326:21)
    at HTMLScriptElement.script.onload (http://127.0.0.1:24286/appservice/appservice?t=1587292098445:1338:20)

**Comment by Simon-wu** [comment]
注释掉这个就好，因为微信版本更新。这个相关的API失效了

**Comment by Simon-wu** [comment]
在threejs你们搜索Mf
